config/routes.rb
Residence::Application.routes.draw do
   devise_for :apartments
   devise_for :staffs

   root to: "pages#home"

   get '/home', to: 'pages#home'

   resources :users
   resources :staffs

   resources :tenants do
      get 'promote_to_staff_form', on: :member
      patch 'promote_to_staff', on: :member
   end

   resources :apartments do
      resources :apartment_statuses
      resources :tenants do
         patch 'relocate', on: :member 
      end
   end

   resources :tickets do 
      delete 'destroy_multiple', on: :collection
   end

   resources :violations

   resources :schedules do
      get 'unscheduled_months', on: :collection
   end

   resources :schedule_entries
   resources :schedule_configurations
   resources :shifts

end

app/models/tenant.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  fname           :string(255)
#  lname           :string(255)
#  username        :string(255)
#  password_digest :string(255)
#  email           :string(255)
#  phone_primary   :string(255)
#  phone_secondary :string(255)
#  roles           :text
#  apartment_id    :integer
#  current_role    :string(255)
#  tenant          :boolean          default(FALSE)
#

class Tenant < User
   

   default_scope -> { where(tenant: true) }
   default_scope -> { order(:lname) }

   belongs_to :apartment

   before_create :set_as_tenant


   validates_presence_of :apartment_id

   # Accepts either an Apartment model or just it's id.
   def lives_in?(apartment)
      if apartment.instance_of? Apartment
         self.apartment_id == apartment.id
      else
         self.apartment_id == apartment
      end
   end


   def remove
      if roles.empty?
         self.destroy
      else
         self.tenant = false
         self.save
      end
   end
   

   private

   def set_as_tenant
      self.tenant = true
   end

end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController

   before_action :set_apartment, except: [:promote_to_staff_form, :promote_to_staff]
   before_action :set_tenant, only: [:promote_to_staff_form]


   def create
      @apartments = Apartment.all
      @tenant = @apartment.tenants.create(tenant_params)
      if @tenant.valid?
         @message = {success: "Tenant has been added"}
      end
   end


   def edit
      @tenant = @apartment.tenants.find_by(id: params[:id])
   end


   def update
      @tenant = @apartment.tenants.find_by(id: params[:id])
      if @tenant.update(tenant_params)
         redirect_to @apartment, notice: "Tenant has been updates."
      else
         render :edit
      end
   end


   def destroy
      tenant = @apartment.tenants.find_by(id: params[:id])
      redirect_to @apartment, notice: "Tenant has been removed." if tenant.remove
   end


   def relocate
      # TODO relocate action: When I add feature to allow managers to own their own apartments...
      # TODO make sure to do this through the managers association.
      
      @tenant = @apartment.tenants.find_by(id: params[:id])
      @tenant.apartment_id = params[:new_apartment_id]
      if @tenant.save
         flash[:success] = "Tenant has been relocated." 
      else 
         flash[:error] = "Error occured."
      end
      redirect_to @apartment
   end


   def promote_to_staff_form
      # Unscope because the user is still a tenant at this point.
      @tenant = Staff.unscoped.find_by(id: params[:id])
   end


   def promote_to_staff
      # Find through Staff because I want the validations for staff fields.
      # Unscope because the user is still a tenant at this point.
      @tenant = Staff.unscoped.find_by(id: params[:id])

      if @tenant.update(promote_to_staff_params)
         redirect_to promote_to_staff_form_tenant_path(@tenant), 
                     notice: "Tenant has been added to staff."
      else 
         render 'promote_to_staff_form'
      end
   end


private

   def tenant_params
      params.require(:tenant)
            .permit(:fname, :lname, :email, :phone_primary, :phone_secondary)
   end


   def promote_to_staff_params
      params.require(:staff)
            .permit(:username, :password, :password_confirmation, roles: [])
   end

   def set_apartment
      @apartment = Apartment.find_by(id: params[:apartment_id])
   end


   def set_tenant
      @tenant = Tenant.find_by(id: params[:id])
   end
end

app/helpers/tenants_helper.rb
module TenantsHelper
   def tenant_form(apt, tenant, options={})

      title = tenant.new_record? ? "New Tenant" : "Edit Tenant"
      btn_label = tenant.new_record? ? "Add Tenant" : "Update Tenant"

      content_tag(:div, :class => 'bg-gray-lighter') do
         raw( # Don't for the raw inside blocks!
            content_tag(:h3, title) +

            simple_form_for([apt, tenant], options) do |f|
               raw( # Don't for the raw inside blocks!
                  f.input(:fname, label: "First Name", required: false) +
                  f.input(:lname, label: "Last Name", required: false)  +
                  f.input(:email)                      +
                  f.input(:phone_primary)              +
                  f.input(:phone_secondary)            +
                  f.submit(btn_label, :class => 'btn btn-primary')   
               )
            end
         )
      end
   end
end

app/views/tenants/_relocate_link.html.erb
<span class='dropdown'>
   <a href="#" class="dropdown-toggle" data-toggle="dropdown"> relocate <b class='caret'></b> </a>
   <ul class='dropdown-menu dropdown-menu-long bg-gray-lighter-no-pad '>
      <% @apartments.delete_if { |a| tenant.lives_in?(a) }.each do |a| %>
      <li>
      <%= link_to a.number, 
            relocate_apartment_tenant_path(apartment, tenant, new_apartment_id: a.id), 
            method: :patch, data: { confirm: "Really relocate tenant?" } %>
      </li>
      <% end %>
   </ul>
</span>

app/views/tenants/create.js.erb
$("#tenant-form-message").html("")
$("#tenant-form span.error").remove()
$("#tenant-form .field_with_errors").removeClass("field_with_errors")
<% if @tenant.valid? %>
   $("#tenant-form-message").html("<%= j content_message(@message) %>").delay(5000).fadeOut()
   $("ul#tenants").append("<%= j render 'apartments/tenant', apartment: @apartment, tenant: @tenant %>")
<% else %>
   $("#tenant-form").html("<%= j tenant_form(@apartment, @tenant, remote: true) %>")
<% end %>

app/views/tenants/edit.html.erb
<%= tenant_form(@apartment, @tenant) %>

app/views/tenants/promote_to_staff_form.html.erb
<div class='bg-gray-lighter'>
   <h2> Add This Tenant To Staff </h2>
   <p> <i> <%= @tenant.name %> </i> </p>
   <%= simple_form_for @tenant, url: promote_to_staff_tenant_path(@tenant) do |f| %>
      <%= f.input :username, required: true %>
      <%= f.input :password, required: true %>
      <%= f.input :password_confirmation %>

      <%= f.input :roles, label: false do %>
         <%= f.collection_check_boxes :roles, Staff::ROLES, :to_s, :humanize do |b| %>
            <%= b.label { b.check_box + b.text } %>
         <% end %> 
      <% end %> <br />

      <%= f.submit "Submit", class: 'btn btn-primary' %>
   <% end %>
</div>