config/routes.rb
Residence::Application.routes.draw do
   devise_for :apartments
   devise_for :staffs

   root to: "pages#home"

   get '/home', to: 'pages#home'

   resources :users
   resources :staffs

   resources :tenants do
      get 'promote_to_staff_form', on: :member
      patch 'promote_to_staff', on: :member
   end

   resources :apartments do
      resources :apartment_statuses
      resources :tenants do
         patch 'relocate', on: :member 
      end
   end

   resources :tickets do 
      delete 'destroy_multiple', on: :collection
   end

   resources :violations

   resources :schedules do
      get 'unscheduled_months', on: :collection
   end

   resources :schedule_entries
   resources :schedule_configurations
   resources :shifts

end

app/models/schedule.rb
# == Schema Information
#
# Table name: schedules
#
#  id              :integer          not null, primary key
#  year            :integer
#  month           :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  interval_length :integer          default(0)
#  month_position  :integer
#

class Schedule < ActiveRecord::Base
   include Schedulable

   has_many :entries, class_name: ScheduleEntry, dependent: :destroy

   validates_presence_of :month, :year, :interval_length, :month_position
   validates_uniqueness_of :month, scope: :year

   default_scope -> { order(:month_position) }

   after_initialize :capitalize_month



   # Returns months for a specific year that a schedule hasn't been created for yet.
   def self.unscheduled_months_for(year)
      scheduled_months = Schedule.where(year: year).pluck(:month)
      Date::MONTHNAMES.slice(1,12) - scheduled_months
   end


   # Returns the length of the last interval for this schedule
   def last_interval_length
      entries.select("DISTINCT(date)").where(day_or_night: 'day', interval_position: entries.maximum(:interval_position)).count
   end

private

   def capitalize_month
      self.month.capitalize! unless self.month.blank?
   end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

   def index
      # TODO If current_user is a guard, then only retrieve published schedules.
      @schedules = Schedule.all.order(:year)
   end


   def show
      @entries = schedule.entries.order(:date, :shift_id).includes(:shift, :staff)
      @entries = @entries.where(staff_id: current_user.id) if params[:personal_view]

      @schedules_for_same_year = Schedule.where(year: schedule.year)
      @last_months_schedule = schedule.last_months_schedule
      @next_months_schedule = schedule.next_months_schedule

      gon.schedules_path = schedules_path
   end


   def new
      if month_selected?
         @schedule_form = ScheduleForm.new(params[:month], year: params[:year], interval_length: params[:interval_length])
         @rotation      = @schedule_form.rotation
         @guards        = Staff.guards
         @shifts        = Shift.all
      end
   end


   def create
      @schedule_form = ScheduleForm::Submission.new(params[:schedule][:month], year: params[:schedule][:year])
      #binding.pry
      if schedule = @schedule_form.submit(params[:schedule])
         redirect_to edit_schedule_path(schedule)
      else
         flash[:error] = "Form is invalid."
         render :new
      end
   end


   def edit
      @entries = schedule.entries.order(:date, :shift_id).includes(:shift)
      @guards = Staff.guards
      @entries_grouped_by_day = @entries.group_by { |e| e.date }.values

      @schedules_for_same_year = Schedule.where(year: schedule.year)
      @last_months_schedule = schedule.last_months_schedule
      @next_months_schedule = schedule.next_months_schedule

      gon.schedules_path = schedules_path
   end


   def update
      @schedule_form = ScheduleForm::Update.new(params[:id])
      @schedule_form.submit(params[:schedule])

      flash[:success] = "Schedule has been updated"
      redirect_to :back
   end



   # JSON
   def unscheduled_months
      months = Schedule.unscheduled_months_for(params[:year])
      respond_to do |format|
         format.json { render json: months }
      end
   end


private

   def schedule
      @schedule ||= Schedule.find_by(id: params[:id])
   end

   def month_selected?
      params[:month] && !params[:month].blank?
   end

end

app/helpers/schedules_helper.rb
module SchedulesHelper

   def sch_form_month_options
      Schedule.unscheduled_months_for(Time.now.year).map { |m| [m, m] }
   end


   # Returns only day shift entries.
   def day_shift_entries_for(day)
      day.select { |e| e.day_shift? }
   end


   # Returns only night shift entries.
   def night_shift_entries_for(day)
      day.select { |e| e.night_shift? }
   end


   # Displays the label for a particular day in the schedule form
   def schedule_day_label(date)
      Date::DAYNAMES[date.wday] + " " + date.to_formatted_s(:long)
   end


   # Used in #show to display schedule for a single day.
   def schedule_for_day(entries, time_shift)
      html = ""
      entries.each do |e|
         if e.day_or_night == time_shift
            html += content_tag(:u, e.shift_name)
            html += content_tag(:p, e.staff_name, :class => 'assigned-staff')
         end
      end
      raw(html)
   end

end

app/views/schedules/_change_schedule_form.html.haml
= form_tag do
  = collection_select :not_used, :not_used, schedules, :id, :month
  %br
  = link_to "Change Month", schedule_path(schedules.first), class: 'btn btn-small'

app/views/schedules/_meta_data_form.html.haml
= form_tag new_schedule_path, method: :get do
  = label_tag  :month, "Select month:"
  = select_tag :month, options_for_select(sch_form_month_options, params[:month])
  = label_tag :year, "Select year:"
  = select_tag :year, options_for_select([Time.now.year, Time.now.next_year.year], params[:year])
  = label_tag :interval_length, "Number of days between rotations:"
  = text_field_tag :interval_length, params[:interval_length] || ScheduleForm.default_interval_length
  %br= submit_tag "Submit", class: 'btn'

app/views/schedules/_month_controls.html.haml
%h2#month-controls
  = link_to "<", poly_path(last_months_schedule) if last_months_schedule
  = "#{schedule.month} #{schedule.year}  Schedule"
  = link_to ">", poly_path(next_months_schedule) if next_months_schedule

app/views/schedules/_schedule.html.haml
%tr
   %td= schedule.year
   %td= link_to schedule.month, schedule_path(schedule)
   %td= link_to 'edit', edit_schedule_path(schedule)

app/views/schedules/_schedule_form_edit_time_shift.html.haml
= day_fields.fields_for time_shift do |time_shift_f|

   - time_shift_recs.each_with_index do |record, record_index|

      = time_shift_f.fields_for "shift-#{record_index}" do |shift_f|
         = shift_f.label :staff, record.shift_name
         = shift_f.collection_select :staff, guards, :id, :name, selected: record.staff_id, include_blank: true
         = shift_f.hidden_field :entry_id, value: record.id

app/views/schedules/_schedule_form_time_shift.html.haml
= interval_fields.fields_for time_shift do |time_shift_fields|
   - shifts.each do |shift|
      = time_shift_fields.fields_for "shift-" + shift.name do |sf|
         = sf.label :staff, shift.name
         = sf.select :staff, guards.map { |g| [g.name, g.id] }, include_blank: true
         = sf.hidden_field :shift, value: shift.id
         = sf.hidden_field :dates, value: interval.dates.join(",")
         = sf.hidden_field :day_or_night, value: local_assigns[:time_shift] == :day_shift ? 'day' : 'night'
         = sf.hidden_field :interval_position, value: @schedule_form.rotation.index(interval)

app/views/schedules/edit.html.haml
= provide(:title, "Edit Schedule")

//.row-with-margin
//  %h2.text-center= "#{@schedule.month} #{@schedule.year}"

.row
  .span12
    = render 'month_controls', schedule: @schedule, 
          last_months_schedule: @last_months_schedule, 
          next_months_schedule: @next_months_schedule

.row
  // Form doesn't actually get posted. Submit button is actually a link to schedules#show.
  .span4#choose-schedule
    = render 'change_schedule_form', schedules: @schedules_for_same_year


.row-with-margin
  .span4
    %h4 
      %b Day Shift

  .span4
    %h4
      %b Night Shift


= form_for @schedule do |f|

  = f.hidden_field :year, value: @schedule.year
  = f.hidden_field :month, value: @schedule.month

  = f.fields_for :entries do |entries_f|

    - @entries_grouped_by_day.each_with_index do |entries_for_day, day_index|

      <!-- Day Row -->
      .bg-gray-lighter.row-with-margin.day-row

        <!-- Day Fields -->
        = entries_f.fields_for "day-#{day_index}" do |dayf|

          .span4.day-shift
            - time_shift_partial_assigns = { day_fields: dayf, 
                                              guards: @guards, 
                                              time_shift: :day_shift, 
                                              time_shift_recs: day_shift_entries_for(entries_for_day) }

            = render 'schedule_form_edit_time_shift', time_shift_partial_assigns


          .span4.night-shift
            - time_shift_partial_assigns[:time_shift]      = :night_shift
            - time_shift_partial_assigns[:time_shift_recs] = night_shift_entries_for(entries_for_day)
            = render 'schedule_form_edit_time_shift', time_shift_partial_assigns


          .span3.date= schedule_day_label(entries_for_day.first.date)

  %br
  %br
  = f.label :published, "Publish?"
  = f.check_box :published?
  %br
  %br
  %br

  = f.submit "Update Schedule", class: 'btn btn-primary'

app/views/schedules/index.html.haml
- provide(:title, "Schedule Index")

%h2 Schedules

%table.display.data-table-gem
   %thead
      %tr
         %th Year
         %th Month
         %th.not-sortable

   %tbody
      = render @schedules

app/views/schedules/new.html.haml
- provide(:title, "New Schedule")

%h2 New Schedule

.row
   .span5#meta-data-form
      = render 'meta_data_form'

- unless params[:month].blank?

   #schedule-form
      .row
         .span4 
            %h3 Day Shift
         .span4 
            %h3 Night Shift

      = form_for :schedule, url: schedules_path  do |f|

         = f.hidden_field :month, value: @schedule_form.month
         = f.hidden_field :year, value: @schedule_form.year
         = f.hidden_field :interval_length, value: @schedule_form.interval_length

         = f.fields_for :entries do |e|
            - @rotation.each_with_index do |i, c|

               <!-- Interval Row -->
               .interval.row-with-margin.bg-gray-lighter
                  = e.fields_for "interval" + c.to_s do |intf|

                     - time_shift_partial_assigns = { interval_fields: intf, interval: i, time_shift: :day_shift, shifts: @shifts, guards: @guards }

                     <!-- Day Shift Col -->
                     .day-shift.span4
                        = render 'schedule_form_time_shift', time_shift_partial_assigns

                     <!-- Night Shift Col -->
                     .night-shift.span4
                        - time_shift_partial_assigns[:time_shift] = :night_shift
                        = render 'schedule_form_time_shift', time_shift_partial_assigns

                  %span.span3.interval-range-text= i.range_text
                  <!-- End Interval Row -->
         %br
         %br
         = f.label     :published?, "Publish?"
         = f.check_box :published?
         %br
         %br
         %br
         = f.submit "Submit Schedule", class: 'btn btn-primary'

   <!-- End Schedule Form Div. -->

app/views/schedules/show.html.haml
- provide(:title, "View Schedule")

.row
  .span12
    = render 'month_controls', schedule: @schedule, 
          last_months_schedule: @last_months_schedule, 
          next_months_schedule: @next_months_schedule

.row
  // Form doesn't actually get posted. Submit button is actually a link to schedules#show.
  .span4#choose-schedule
    = render 'change_schedule_form', schedules: @schedules_for_same_year

  .span4.pull-right
    = link_to "Personal View", schedule_path(@schedule, personal_view: true)

.row
  .span12#calendar
    = calendar_for @entries, year: @schedule.year, month: month_number(@schedule.month) do |calendar|
      = calendar.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')
      - calendar.day do |date, entries|
        .day= date.day

        .schedule-for-day
          .day-shift
            - unless entries.blank?
              %p
                %b Day Shift 
              = schedule_for_day(entries, 'day') 
          .night-shift
            - unless entries.blank?
              %p 
                %b Night Shift
              = schedule_for_day(entries, 'night')