config/routes.rb
Residence::Application.routes.draw do
   devise_for :apartments
   devise_for :staffs

   root to: "pages#home"

   get '/home', to: 'pages#home'

   resources :users
   resources :staffs

   resources :tenants do
      get 'promote_to_staff_form', on: :member
      patch 'promote_to_staff', on: :member
   end

   resources :apartments do
      resources :apartment_statuses
      resources :tenants do
         patch 'relocate', on: :member 
      end
   end

   resources :tickets do 
      delete 'destroy_multiple', on: :collection
   end

   resources :violations

   resources :schedules do
      get 'unscheduled_months', on: :collection
   end

   resources :schedule_entries
   resources :schedule_configurations
   resources :shifts

end

app/models/apartment.rb
# == Schema Information
#
# Table name: apartments
#
#  id              :integer          not null, primary key
#  number          :integer
#  password_digest :string(255)
#  tickets_count   :integer          default(0), not null
#

class Apartment < ActiveRecord::Base
   # Include default devise modules. Others available are:
   # :token_authenticatable, :confirmable,
   # :lockable, :timeoutable and :omniauthable
   devise :database_authenticatable,
          :trackable, :validatable, authentication_keys: [:number]

   #has_secure_password

   has_one :status, class_name: ApartmentStatus, dependent: :destroy
   has_many :tenants, class_name: Tenant, dependent: :destroy
   has_many :tickets, dependent: :destroy

   default_scope -> { order("number") }

   delegate :occupied, :occupied=, :occupied?, :status_start_date, :number_of_tenants, :comment, to: :status, allow_nil: true

   accepts_nested_attributes_for :status

   validates :number, presence: true, numericality: true, uniqueness: true

   after_update :vacate, unless: -> { occupied }



   def state
      occupied ? "Occupied" : "Vacant"
   end

   # Define this method to prevent "no method" 
   # errors when doing authorization.
   def is?(role)
      role.to_s == 'tenant'
   end


   def self.ransackable_attributes(auth_object = nil)
      %w( number ) + _ransackers.keys
   end

private

   def vacate
      tickets.destroy_all
      tenants.destroy_all
   end

end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController

   def index
      @apartments = Apartment.includes(:status)
   end
   

   def show
      @tenants = apartment.tenants
      @apartments = Apartment.all
      @tickets = apartment_tickets
   end
   

   def new
      @apartment = Apartment.new(status: ApartmentStatus.new)
   end


   def create
      @apartment = Apartment.create(apartment_params)
      if @apartment.valid?
         flash[:success] = "Apartment has been created"
         redirect_to @apartment
      else
         render :new
      end
   end


   def edit
      apartment
   end


   def update
      if apartment.update(apartment_params)
         redirect_to apartment, notice: "Updated"
      else 
         render 'edit'
      end
   end



   private

   def apartment_params
      params.require(:apartment)
            .permit(:number, :password, :password_confirmation, status_attributes: [:occupied, :status_start_date, :comment])
   end

   def apartment
      @apartment ||= Apartment.find_by(id: params[:id])
   end

end

app/helpers/apartments_helper.rb
module ApartmentsHelper
   def status_start_date_label(apartment, f)
      #status = apartment.occupied ? "Occupied" : "Vacant"

      content_tag(:label) do
         raw(
            content_tag(:span, apartment.state, id: 'status-label') +
            " since: (yyyy-mm-dd)"
         )
      end
   end


   def apartment_label(apartment)
      alert_type = apartment.occupied ? 'alert-info' : 'alert-error'

      content_tag(:div, id: "apartment-label", :class => "text-center alert #{alert_type}") do
         raw(
            content_tag(:h3, apartment.number) +
            content_tag(:h3, apartment.state)
         )
      end
   end


   def apartment_tickets
      if signed_in_as_staff?
         @apartment.tickets.includes(:staff, :violations)
      else
         @apartment.tickets.unpaid.includes(:staff, :violations)
      end
   end
end

app/views/apartments/_apartment.html.erb
<tr>
   <td> </td>
   <td class='text-center'> <%= link_to(apartment.number, apartment) %>  </td>
   <td class='text-center'> <%= apartment.occupied ? "Occupied" : "Vacant" %> </td>
   <td class='text-center'> <%= apartment.status_start_date %> </td>
   <td class='text-center'> <%= truncate(apartment.comment, length: 65, separator: ' ') %> </td>
   <td class='text-center'> <%= apartment.tickets.count %> </td>
   <td class='text-center'> <%= link_to "edit", edit_apartment_path(apartment) %> </td>
</tr>

app/views/apartments/_apartment_form.html.erb
<div class='bg-gray-lighter'>
   <h3 class='text-center'> <%= title %> </h3>
   <%= simple_form_for apartment, html: { class: 'form-horizontal' } do |f| %>

      <%= f.input :number %>
      <%= f.input :password, required: false %>
      <%= f.input :password_confirmation, required: false %>

      <h4>Status Information</h4>

      <%= f.fields_for :status do |s| %>
         <label class='checkbox'>
            <%= s.input :occupied, label: false %> Occupied?
         </label> <br />
         <%= status_start_date_label(apartment, s) %>
         <%= s.input :status_start_date, label: false, as: :string %>
         <%= s.input :comment %>
      <% end %>

      <%= f.submit "Submit", class: 'btn btn-primary' %>

   <% end %>
</div>


<!-- Being used to test Capybara javascript drivers -->

<div id="foobar">
<button id="foo-btn"> Click </button>
<div id="foo-text"> foo </div>
</div>


<script>
   $(document).ready(function() {
      $("#foobar").on('click', "#foo-btn", function() {
         $("#foobar").append("<p id='foo-p'>paragraph</p>")
      })
   })
</script>

app/views/apartments/_status_box.html.erb
<div id="apartment-status-box" class='bg-gray-lighter'>
   <p><%= apartment.state %> since: <%= apartment.status_start_date.try(:to_formatted_s, :long) %></p> 
   <p><%= apartment.comment %></p>
   <p><%= link_to "Edit apartment information", edit_apartment_path(apartment) %></p>
</div>

app/views/apartments/_tenant.html.erb
<li id='<%= dom_id(tenant) %>'>
   <p><%= content_tag(:strong, tenant.name) %></p>
   <p><%= "Email: #{tenant.email}" %></p>
   <p><%= "Primary #: #{tenant.phone_primary}" %></p>
   <p><%= "Secondary #: #{tenant.phone_secondary}" %></p>
   <%= link_to "edit", edit_apartment_tenant_path(apartment, tenant) %> |
   <%= link_to "delete", [apartment, tenant], method: :delete, data: { confirm: "Really delete tenant from database?" } %> |
   <%= render 'tenants/relocate_link', tenant: tenant, apartment: apartment %> |
   <%= link_to "add to staff", promote_to_staff_form_tenant_path(tenant) %>
</li>

app/views/apartments/edit.html.erb
<% provide(:title, "Edit Apartment") %>

<%= render 'apartment_form', apartment: @apartment, title: "Edit this apartment" %>

app/views/apartments/index.html.erb
<% provide(:title, "Apartment Index") %>

<h2> Apartments </h2>
<table class="display data-table-gem">
<thead>
   <tr>
      <th class="not-sortable"> <input type="checkbox" id="select-all-entries-toggle" /> </th>
      <th class="num-html"> #  </th>
      <th> Status              </th>
      <th> Since               </th>
      <th> Comment             </th>
      <th> Tickets             </th>
      <th class="not-sortable"></th> <!-- Edit column -->       
   </tr>
</thead>
<tbody>
   <%= render @apartments %>
</tbody>
</table>

app/views/apartments/new.html.erb
<% provide(:title, "New Apartment") %>

<%= render 'apartment_form', apartment: @apartment, title: "Create a new apartment"  %>

app/views/apartments/show.html.erb
<% provide(:title, "Apartment Status") %>

<div class='row'>

   <div class='span2'>
      <%= apartment_label(@apartment) %>
   </div>

   <div class='span4 pull-right'>
      <%= render 'status_box', apartment: @apartment %>
   </div>
</div>


<div class='row-with-margin'>
    <!-- Column 1 -->
   <div class='span4'>
      <h3> Tenants </h3>
      <div class="accordion-heading">
         <a class="accordion-toggle" data-toggle="collapse" href="#new-tenant-form-accordion">
            Add new tenant
         </a>
      </div>
      <ul id='tenants'>
         <%= render partial: 'tenant', collection: @tenants, locals: { apartment: @apartment } %>
      </ul>
   </div> <!-- End Column 1 -->

    <!-- Column 2 -->
   <div class='span5'>
      <div id="new-tenant-form-accordion" class="accordion-body collapse">
         <div class="accordion-inner">
            <span id='tenant-form-message'></span>
            <div id='tenant-form'>
               <%= tenant_form(@apartment, Tenant.new, remote: true) %>
            </div>
         </div>
      </div>
   </div> <!-- End Column 2 -->
</div>


<div class='row-with-margin'>
   <div class='span12'>
      <h3> Tickets </h3>
      <div id="ticket-result-message"> </div> 
      <%= render 'tickets/tickets', tickets: @tickets %>
   </div>
</div>