config/routes.rb
Residence::Application.routes.draw do
   devise_for :apartments
   devise_for :staffs

   root to: "pages#home"

   get '/home', to: 'pages#home'

   resources :users
   resources :staffs

   resources :tenants do
      get 'promote_to_staff_form', on: :member
      patch 'promote_to_staff', on: :member
   end

   resources :apartments do
      resources :apartment_statuses
      resources :tenants do
         patch 'relocate', on: :member 
      end
   end

   resources :tickets do 
      delete 'destroy_multiple', on: :collection
   end

   resources :violations

   resources :schedules do
      get 'unscheduled_months', on: :collection
   end

   resources :schedule_entries
   resources :schedule_configurations
   resources :shifts

end

app/views/layouts/_flash_messages.html.erb
<span id='main-flash-messages'>
<% flash.each do |type, msg| %>
   <%= content_tag(:div, class: "alert alert-#{type}") do %> 
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert">&times;</button>
   <% end %>
<% end %>
</span>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">

      <!-- Responsive button when window gets small -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
      </a>
      <!-- end Responsive button -->

      <nav>
        <ul class="nav pull-left">
           <!-- add if signed in. -->
           <li> 
              <%= link_to '#' do %> 
                 <i class="icon-home icon-white"></i> 
              <% end %>
           </li>
        </ul>

        <div class="nav-collapse">
           <ul class="nav pull-right">

              <li class='dropdown'> 
                 <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Tickets <b class="caret"></b>
                 </a>
                 <ul class="dropdown-menu">
                    <li> <%= link_to "All", tickets_path %> </li>
                    <li> <%= link_to "New", new_ticket_path %> </li>
                 </ul>
              </li>

              <li class='dropdown'> 
                 <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Apartments <b class="caret"></b>
                 </a>
                 <ul class="dropdown-menu">
                    <li> <%= link_to "All", apartments_path %> </li>
                    <li> <%= link_to "New", new_apartment_path %> </li>
                 </ul>
              </li>

              <li class='dropdown'>
                 <a href="#" class='dropdown-toggle' data-toggle="dropdown">
                    Staff <b class='caret'></b>
                 </a>
                 <ul class='dropdown-menu'>
                    <li> <%= link_to "All", staffs_path %> </li>
                    <li> <%= link_to "New", new_staff_path %> </li>
                 </ul>
              </li>

              <li> <%= link_to "Sign in", new_staff_session_path %> </li>

               <!-- Account Dropdown. For reference. -->
               <li id="fat-menu" class="dropdown">
                 <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                   Account <b class="caret"></b>
                 </a>
                 <ul class="dropdown-menu">
                   <li><%= link_to "Change info" %></li>
                   <li class="divider"></li>
                   <li>
                     <%= link_to "Sign out", destroy_staff_session_path, method: :delete %>
                   </li>
                 </ul>
               </li>
               <!-- End Account Dropdown. -->

           </ul> <!-- end right nav -->
        </div> <!-- end nav-collapse -->
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container

      / Responsive button when window gets small
      %a.btn.btn-navbar{'data-toggle' => "collapse", 'data-target' => ".nav-collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

     
      %nav
        %ul.nav.pull-left
          / add if signed in.
          %li
            = link_to '#' do
              %i.icon-home.icon-white

        / Main navigation
        .nav-collapse
          %ul.nav.pull-right

            / Tickets
            %li.dropdown
              %a.dropdown-toggle{:href => "#", 'data-toggle' => "dropdown"}
                Tickets 
                %b.caret
              %ul.dropdown-menu
                %li= link_to "All", tickets_path
                %li= link_to "New", new_ticket_path

            / Apartments
            %li.dropdown
              %a.dropdown-toggle{:href => "#", 'data-toggle' => "dropdown"}
                Apartments 
                %b.caret
              %ul.dropdown-menu
                %li= link_to "All", apartments_path
                %li= link_to "New", new_apartment_path

            / Staff
            %li.dropdown
              %a.dropdown-toggle{:href => "#", 'data-toggle' => "dropdown"}
                Staff 
                %b.caret
              %ul.dropdown-menu
                %li= link_to "All", staffs_path
                %li= link_to "New", new_staff_path

            / Schedules
            %li.dropdown
              %a.dropdown-toggle{:href => "#", 'data-toggle' => "dropdown"}
                Schedules
                %b.caret
              %ul.dropdown-menu
                %li= link_to "All", schedules_path
                %li= link_to "New", new_schedule_path
                %li= link_to "Schedule Configuration", schedule_configurations_path

            / Sign in
            %li= link_to "Sign in", new_staff_session_path

            / Account
            %li#fat-menu.dropdown
              %a.dropdown-toggle{:href => "#", 'data-toggle' => "dropdown"}
                Account 
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Change info"
                %li.divider
                %li= link_to "Sign out", destroy_staff_session_path, method: :delete

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title= full_title(yield(:title))
    = include_gon(watch: true)
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag params[:controller] + "/shared"
    = javascript_include_tag params[:controller] + "/" + params[:action]
    = csrf_meta_tags

    / IE 8 and lower do not support HTML5 (which Rails uses by default), so below if statement is necessary.

    / [if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
%body
  = render 'layouts/header'
  .container
    = render 'layouts/flash_messages'
    = yield
    = debug(params) if Rails.env.development?